version: '3'
services:
  web:
    image: gopishankar1/counterweb:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    environment:
      FLASK_ENV: development
  redis:
    image: "redis:alpine"
